import React from 'react'
import Providers from './libs/utils/Provider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='bg-zinc-900'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
